### PR TITLE
Hello World Servlet example

### PR DESCRIPTION
**Pull request by RommelTJ**
## Description

This adds an example for how to use the Alexa SkillServlet. It is essentially the same as the Hello World example, but instead of being deployed as a lambda function, it extends the `SkillServlet` and is meant to be deployed as a WAR file. 

## Motivation and Context

See: https://github.com/alexa/alexa-skills-kit-sdk-for-java/issues/94

This repository is missing a Servlet example for deploying an Alexa Custom Skill as a Web Service. While there is some documentation from Amazon [here](https://developer.amazon.com/docs/custom-skills/deploy-a-sample-skill-as-a-web-service.html) and [here](https://developer.amazon.com/docs/custom-skills/use-the-alexa-skills-kit-samples.html#getting-the-source-code-for-the-samples-and-java-library), these are incomplete as they refer to the ASK`1.x.x` SDK.

## Testing

I don't see any tests bundled with the repository, but I ran my own unit tests and deployed the app to a Tomcat server. 

## Screenshots (if appropriate)
N/A

## Types of changes

- [x] New feature (non-breaking change which adds functionality)

## Checklist

- [x] My code follows the code style of this project
- [x] My change requires a change to the documentation
- [x] I have updated the documentation accordingly
- [x] I have read the **README** document
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed

## License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

[issues]: https://github.com/alexa/alexa-skills-kit-sdk-for-java/issues
[license]: http://aws.amazon.com/apache2.0/
[cla]: http://en.wikipedia.org/wiki/Contributor_License_Agreement

### CODE REVIEW

**Comment by RommelTJ** [comment]
I couldn't find any contribution guidelines, but I took a look at merged Pull Requests and I think I submitted the PR as requested. Please let me know if you have any questions.

**Comment by breedloj** [comment]
I agree that having a servlet example would be extremely beneficial. The developer section of the pom.xml will need to match that of our other POMs for legal reasons. If you can make that change and confirm you are submitting under the Apache 2.0 License I'll see about getting this merged in. Thanks for the contribution!

**Comment by RommelTJ** [comment]
Thank you, @breedloj. I made the modifications to `pom.xml`. The only thing that doesn't match is the build settings and the packaging, which have to be different since it has to build as a `war`. Let me know if I need to change anything else.

Oh, and just to be explicit, I am submitting this change under the Apache 2.0 License.

**Comment by breedloj** [comment]
Looks good to me! Merging.

**Pull request merged**
