### PR TITLE
Multi-module project structure and build

### PR DESCRIPTION
**Pull request by psgrove**
This pull request relates to the question I posted on the [forum](https://forums.developer.amazon.com/questions/37225/how-does-the-java-sdk-get-built.html) and the subsequent discussion. This pull request represents what I think a correct multi project structure of the code should look like so that the SDK can be built as a standalone jar. Also the samples depend on the SDK project not any external build of the SDK (Gradle issue only). It would be good for the dev team to use branches to actually show what code is in the versioned SDK jar available in Maven central. I suggest this goes on a new Branch not the master.
As part of the restructure the actual real dependencies of the SDK and samples has been cleaned up.
Removed Javadoc as this should be generated from source and not added to Git

### CODE REVIEW

**Comment by jtgrassie** [comment]
This looks good to me. Why is it not being merged?

**Comment by jjaquinta** [comment]
I don't think Amazon actually accepts code submissions. It gets into interesting legal questions. This isn't really here as a community involved project, just a place for Amazon to publish their code.

**Comment by jtgrassie** [comment]
Well, even if they don't merge, at least the rest of us can use.

**Comment by psgrove** [comment]
It would be nice to get a response from Amazon dev team on this. It seems crazy that they publish the SDK to maven central yet no tags or release are in Github so we have no way of actually knowing what is in the versioned jar unless you decompile the source! The SDk is also not keeping up with the feature being release in Alexa. Either keep it updated or engage with the community and except pull requests?

**Comment by fzakaria** [comment]
We don't we just follow another fork as the main repo ?
This is a common thing in OSS.
They are under no obligation to offer anything

**Comment by jjaquinta** [comment]
The Amazon Dev team does not respond. Only the support team make public statements. And they don't usually participate here.

But you are right, there's nothing stopping you doing your own library. Hard to get traction. Just about every developer likes writing their own ASK harness and disagrees with just about everyone else's approach. Shrug.

There is something to be said for a non-Amazon harness, though, now that Google have announced there will be a SDK for Google Home. That way it could be adapted after the SDK release to support Google Home as well. I just [did a post](https://www.linkedin.com/groups/8336219/8336219-6189399675561336833) suggesting people use how [SubWar](https://github.com/jjaquinta/EchoSubWar) separated things as an example. If you want to build a harness into that you are welcome. That is public domain and I'm happy to accept pull requests.

**Comment by fzakaria** [comment]
It's been a while since I used this SDK but wasn't it mainly Jackson data
types and a URL route to actions?
Don't see how it can disagree that much :)

**Comment by jtgrassie** [comment]
It's better for developers to have an officially supported SDK. By putting the code on github, it allows other developers to easily submit bug fixes and suggestions / enhancements (like this worthy pull request) that Amazon can review and incorporate or not. Fine is Amazon don't want to merge, the rest of us can still contribute and share our enhancements. Building a ground up completely different library is not the aim here.

**Comment by rvanderwerf** [comment]
I agree I wrote my own impl for audio directives and added gradle support to mine as well. I'd be game for contributing to an active fork of this code somewhere else if Amazon isn't interested in supporting his sdk any longer. I see they are only doing work on the node sdk right now :(

We could make a new github org to keep the master one and mark people as contributors if anyone is interested I'd be game to set this up.

**Comment by psgrove** [comment]
All well and good forking the official repo and building off this, but my main concern is that the Alexa Skills kit docs still point to the original one, the forked repo will not be able to publish to Maven central an updated SDK. If we really want to do this it would have to be a hard fork change group id and publish as a new opensource alternative to the official SDK in Maven central.

**Comment by jtgrassie** [comment]
@rvanderwerf I have no intention of contributing solely to an "unofficial" repository as you are suggesting and would far rather submit PR's here on the official repo so that even if Amazon don't merge the PR's, at least others can clone the supported repo and merge in the PR's themselves, selectively. @psgrove highlighted an important issues with maintaining a hard fork. Lastly, I suspect Amazon are working on a new round of updates to all languages Alexa sdk's which is why they probably don't want to merge in just the java sdk changes, namely they want all the language sdk's to have the same feature set, which makes sense.

**Comment by rvanderwerf** [comment]
yep I intent on keeping this in sync with this master in case they do merge in or start updating this again. I'm not sure why that's not happening but personally I need to move on with making apps. Anyone who wants to send PRs there as well is welcome so you can run the latest. I think that would be useful to have a more bleeding edge version for those interesting in trying some of the newer functionality.

**Comment by fzakaria** [comment]
For maven installations you can leverage
https://jitpack.io/
Without having to change the groupId

On Oct 24, 2016 8:26 AM, "Ryan Vanderwerf" <notifications@github.com> wrote:

yep I intent on keeping this in sync with this master in case they do merge
in or start updating this again. I'm not sure why that's not happening but
personally I need to move on with making apps. Anyone who wants to send PRs
there as well is welcome so you can run the latest. I think that would be
useful to have a more bleeding edge version for those interesting in trying
some of the newer functionality.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/amzn/alexa-skills-kit-java/pull/15#issuecomment-255773682>,
or mute the thread

**Comment by sungolivia** [comment]
Hey there, is this PR still active? If so, can you resolve conflicts? There is also v2 SDK out FYI :D Thanks!

**Comment by psgrove** [comment]
I’m happy to spend time looking at this again if Amazon are going to merge it in?

**Comment by psgrove** [comment]
Just checked V2 which now is a modular build so will close.

**Pull request closed without merging**
