### PR TITLE
Fixed some wrong maven config and changed project to only maven module

### PR DESCRIPTION
**Pull request by jasjisdo**
- removed gradle config (mixing maven and gradle is not necessary in to create a fat jar file)
- removed unnecessary plugin management configuration.
- added a configuration for creating a fat (uber) jar with maven shade plugin

### CODE REVIEW

**Comment by astellingwerf** [comment]
Gradle is not necessarily useless. It allows to build without the need to install Maven first.

**Comment by jasjisdo** [comment]
Then you have to install gradle first what is the benefit?
A better way to solve that problem is to use maven wrapper.

**Comment by hazendaz** [comment]
and there is the maven wrapper which does it automatically to get maven in place.  I'm sure gradle has one too.

**Comment by rvanderwerf** [comment]
gradle wrapper solves this too and makes it easier to add custom functionality and publishing as well. I think it's a lot better imo.

**Comment by sungolivia** [comment]
Hey there, is this PR still active? If so, can you resolve conflicts? Thanks!

**Pull request closed without merging**
