### PR TITLE
Added AudioPlayer functionality.

### PR DESCRIPTION
**Pull request by jtgrassie**
Issue #16

### CODE REVIEW

**Comment by rvanderwerf** [comment]
I've merged your PR here https://github.com/vanderfox/alexa-skills-kit-java and added you as a collab (and the other PRS too!) if you want to give it a go!

**Comment by rvanderwerf** [comment]
Hey @jtgrassie I've found some bugs with your audio support I've logged here https://github.com/vanderfox/alexa-skills-kit-java/issues/1 the directives seem OK but the incoming audio requests are throwing exceptions with jackson errors in the sdk.

**Comment by jtgrassie** [comment]
If you'd pulled and merged my head commit you wouldn't see these errors. 
Working perfectly here in a live skill.

**Comment by rvanderwerf** [comment]
Nope there are bugs with sending audio response events, fixes are at https://github.com/vanderfox/alexa-skills-kit-java

**Comment by jtgrassie** [comment]
@rvanderwerf You are not required to return anything from an audio request. The docs are pretty clear that if you do, you can only return certain audio playback messages. 
https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/custom-audioplayer-interface-reference
"Note: When responding to AudioPlayer requests, you can only respond with AudioPlayer directives. The response cannot include any of the standard properties such as outputSpeech. In addition, some requests limit the directives you can use, such as not allowing Play. Sending a response with unsupported properties causes an error. See the request types below for the limits on each request. ."
The error you were getting is because you were sending an incorrect response to a audio player request. If you return nothing at all, they pass through fine.

**Comment by jtgrassie** [comment]
That said, I do like the fact you added responses to audio requests. My only comment would be you should either validate the response is correct for the type of request or perform no check at all. Currently your commit has a mixture of creating its own response (for example on your playback stopped request) and on others returning a user created response. You should also check for null response from user code as the docs do not require a response, hence a user could chose to not respond to the request which would break your code, which is now enforcing a response.

**Comment by rvanderwerf** [comment]
Live testing confirms null/void responses with out a speechletresponse envelope cause Alexa to return SystemError calls. I've confirmed that an empty list returned makes it happy and it doesn't call back with errors, even if no directives are allowed to be returned like PlaybackStopped and SystemError. I tested this on a Tap. I think the docs should clarify this point, returned directives for audio calls are 'optional' however some sort of response envelope appears to be required even if it's empty.

**Comment by jtgrassie** [comment]
If you don't return _anything_ it works fine. If you return a response and without directives, you get system exception. Makes sense as the doc's state you can only return certain responses to audio requests, and these are all audio responses (hence would require directives). I advise you update your changes to allow for both a response to an audio request and no response at all (don't send _anything_ back after receiving a request).
I think you got caught in a rabbit hole as you started returning a response, which was an invalid response based on the types of response allowed, and then assumed you _have_ to return a response, which is not the case.

**Comment by jtgrassie** [comment]
If you pulled and merged my head commit you wouldn't see this error. The
code is working perfectly for me in a live skill.

**Comment by rvanderwerf** [comment]
nope your code doesn't work man, I'm not sure why you can't see it:

  } else if (speechletRequest instanceof PlaybackStartedRequest) {
 +            speechlet.onPlaybackStarted((PlaybackStartedRequest) speechletRequest);
 +        } else if (speechletRequest instanceof PlaybackStoppedRequest) {
 +            speechlet.onPlaybackStopped((PlaybackStoppedRequest) speechletRequest);
 +        } else if (speechletRequest instanceof PlaybackFinishedRequest) {
 +            speechlet.onPlaybackFinished((PlaybackFinishedRequest) speechletRequest);
 +        } else if (speechletRequest instanceof PlaybackNearlyFinishedRequest) {
 +            speechlet.onPlaybackNearlyFinished((PlaybackNearlyFinishedRequest) speechletRequest);
 +        } else if (speechletRequest instanceof PlaybackFailedRequest) {
 +            speechlet.onPlaybackFailed((PlaybackFailedRequest) speechletRequest);
          } else {

=======
// New Audio Interface
 +    void onPlaybackStarted(PlaybackStartedRequest request) throws SpeechletException;
 +    void onPlaybackFinished(PlaybackFinishedRequest request) throws SpeechletException;
 +    void onPlaybackStopped(PlaybackStoppedRequest request) throws SpeechletException;
 +    void onPlaybackNearlyFinished(PlaybackNearlyFinishedRequest request) throws SpeechletException;
 +    void onPlaybackFailed(PlaybackFailedRequest request) throws SpeechletException;
  }
View  

=====

This is code from YOUR pull request above (you keep saying check your HEAD not your branch, but that's not what you submitted in your PR here because PRs come from a branch and it shows this clearly in GH). There null response returned on all of the audio objects and the user has no way to return a SpeechletResponse from a void return type call. This results in Alexa returning with a System Error call because YOUR code is returning null. Since there was no supported added for the SystemError call you would never see the errors happening unless you turned debug on your skill and checked cloudwatch logs. I've fixed that too in my repo as well so if something happens and alexa calls back with and error it is logged so you know it happened.

**Comment by jtgrassie** [comment]
I was never returing a null response from user code. The return type was void for the requests and I never sent any response to a playback request, hence no error. 
Your change adds a return type of SpeechletResponse so always does a return / call in response to every playback request. That is incorrect as per docs. You are not required to send a response from user code when you recieve a audio request. Not sure how I am not being clear on this.

**Comment by phlepper** [comment]
Not sure where I should be asking this question, so I'll start here.  Just started trying out the sample skills and the SDK for AudioPlayer, so forgive me if I'm in the wrong place...

Is there a reason the AudioPlayer and PlaybackController interfaces include Request but don't include Session (e.g., onPlaybackNearlyFinished and onNextCommandIssued) like the standard Speechlet interface does?  Is the Session information available elsewhere when these methods are called?

I'd like to maintain audio information (like current song, next song, playlist info, etc.) to be used to determine the next song to queue.  Seems like Session is the logical place, but I don't see how to get to it from the above methods.  

And according to the documentation, my Speechlet implementation object can't store the information because multiple objects and even multiple servers might support a single Session.

Or am I missing something?

If it makes sense to add them, should I just make the changes and submit a pull request?  Anyone know a good reason *not* to include Session  that would result in me creating extra interfaces (one with Request and Session and the (current) one with just Request)?

Thanks for the help,
phlepper

**Comment by breedloj** [comment]
Closing this since the AudioPlayer interface is now supported in both the v1 and v2 SDKs.

@phlepper The event requests you listed are out of session requests and thus do not have access to session attributes. If you want to store information out of session, the v2 SDK introduces first class support for persisted attributes, as [described here](https://github.com/alexa/alexa-skills-kit-sdk-for-java/wiki/Skill-Attributes#persistent-attributes).

**Pull request closed without merging**
