### PR TITLE
Added support for Skill Builder (Beta) dialog interaction model

### PR DESCRIPTION
**Pull request by INRIX-dion-hutchings**
Updated Dialog directives
Updated Request and Response models to suit
Tried to cover any files I touched with unit tests
Added a working example that demonstrates delegate directive (automatic dialog) or manual elicit and confirm directives.

Please let me know if I can address any issues

### CODE REVIEW

**Comment by mariokorte** [comment]
This one looks really good! Nice work. Please update the SDK for the new Dialog Model!

**Comment by rabejens** [comment]
If an intent has slots that are optional, it looks like I have to check their presence and if they are required on the Java side manually as the initial dialog state is always `null`. Let's say I have the following sample utterances for an intent:

- do {foo}
- do {foo} and {bar}

And {foo} is required but {bar} isn't, when I say "Do Foo", I correctly get the `foo` slot filled and `bar` is `null`. However the dialog state is not `COMPLETED` as I'd expect it, but it is `null` and I couldn't find a way to check if all required slots are filled with a value. Is this by design?

**Comment by marinator86** [comment]
@INRIX-dion-hutchings do you know about the state of this PR? It would be really useful to have it merged.

**Comment by INRIX-dion-hutchings** [comment]
@marinator86 That's a good question.  Am I correct the next step would be a contributor to review, right?

**Comment by daniel-lee-wallylabs** [comment]
Hope this can get merged soon... was building my skill based on the documentation and THEN find out the actual feature is still going through the PR process :(

**Comment by marinator86** [comment]
@INRIX-dion-hutchings could you resolve the conflicts?

**Comment by marinator86** [comment]
@bclement-amazon Hi Brendan, you think there's a chance to get this PR in?

**Comment by sungolivia** [comment]
Hey there, is this PR still active? If so, can you resolve conflicts? Thanks!

**Pull request closed without merging**
